# spring.application.name=patient
# spring.datasource.url=jdbc:postgresql://neondb_owner:npg_jRLZpKb0FC8U@ep-fancy-queen-a1flah4u-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true 

spring.application.name=patient

spring.datasource.url=jdbc:postgresql://ep-fancy-queen-a1flah4u-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_jRLZpKb0FC8U

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect