apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: smart-healthcare
data:
  DB_URL: "jdbc:postgresql://ep-young-lab-an66dqh3-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require"
  CLOUDINARY_CLOUD_NAME: "dktaqzevd"
  SERVICE_DOCTOR_URL: "http://doctor-service:8083"
  SERVICE_PATIENT_URL: "http://patient-service:8082"
  SERVICE_APPOINTMENT_URL: "http://appointment-service:8084"
---
apiVersion: v1
kind: Secret
metadata:
  name: common-secrets
  namespace: smart-healthcare
type: Opaque
stringData:
  DB_USER: "neondb_owner"
  DB_PASS: "npg_oiz0MdPhp2YJ"
  CLOUDINARY_API_KEY: "253631729724245"
  CLOUDINARY_API_SECRET: "O1VOAlMUSgpgxqvOWFWDZ1OBazg"
  AGORA_APP_ID: "e3ac1ce5498d4a60a1c7f264486dc55e"
  AGORA_APP_CERTIFICATE: "07af6fdfe63a42638d994ec4b88c7f6b"
