spring.application.name=telemedicine
server.port=8085

# DB (same Neon pattern)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Service-to-service (optional but recommended)
appointment.baseUrl=${APPOINTMENT_BASE_URL:http://localhost:8080}

# Agora
agora.appId=${AGORA_APP_ID}
agora.certificate=${AGORA_APP_CERTIFICATE}
agora.tokenTtlSeconds=${AGORA_TOKEN_TTL_SECONDS:3600}