apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemedicine-service
  namespace: shc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemedicine-service
  template:
    metadata:
      labels:
        app: telemedicine-service
    spec:
      containers:
        - name: telemedicine-service
          image: shc-telemedicine:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          envFrom:
            - configMapRef:
                name: telemedicine-config
            - secretRef:
                name: telemedicine-secret
