# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: appointment-config
#   namespace: shc
# data:
#   SPRING_PROFILES_ACTIVE: "default"
#   DB_URL: "jdbc:postgresql://ep-young-lab-an66dqh3-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require"

apiVersion: v1
kind: ConfigMap
metadata:
  name: appointment-config
  namespace: shc
data:
  SPRING_PROFILES_ACTIVE: "default"
  DB_URL: "jdbc:postgresql://<YOUR-NEON-HOST>/neondb?sslmode=require"
