# apiVersion: v1
# kind: Secret
# metadata:
#   name: appointment-secret
#   namespace: shc
# type: Opaque
# stringData:
#   DB_USER: neondb_owner
#   DB_PASS: npg_oiz0MdPhp2YJ

apiVersion: v1
kind: Secret
metadata:
  name: appointment-secret
  namespace: shc
type: Opaque
stringData:
  DB_USER: "REPLACE_ME"
  DB_PASS: "REPLACE_ME"
