server.port=8085

# SMTP Configuration (Example for Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ovse756@gmail.com
spring.mail.password=OvseP@756
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.application.name=notification

spring.datasource.url=jdbc:postgresql://ep-fancy-queen-a1flah4u-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_jRLZpKb0FC8U

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect